### ISSUE TITLE
Wrong label for aug 4th / dim 5th

### ISSUE THREAD

**Issue by VinSpee** [KyleAMathews/modularscale#2]
Hi! I love and cherish this module. Today I was implementing a design using the Augmented Fourth / Diminished Fifth (Devil's Interval) and noticed that it's mislabeled in this module as "diminished fourth).

It should be *augmented fourth* or *diminished fifth* for the `Math.sqrt(2)` ratio.

**Comment by KyleAMathews** [comment]
So it should! Fixed in https://github.com/KyleAMathews/modularscale/blob/master/src/index.coffee

**Comment by KyleAMathews** [comment]
BTW, curious if you've tried typography.js yet? It's this module on steroids basically :-)

**Comment by KyleAMathews** [comment]
Pushed a 2.0 with this change as it's a breaking change.

**Comment by VinSpee** [comment]
Thanks for the fix! I have looked into / am considering typography.js - I just have to tie it in to my atomic css lib / component https://github.com/VinSpee/react-shed - I'll give it a go this week. Thanks!

**Comment by KyleAMathews** [comment]
Oh cool! Lemme know if you have any questions! Would love to help make this
happen :-)
